name: Publish Image Using Semver Tag

on:
  push:
    tags:
      - v*

jobs:
  build_staging:
    name: Publish Staging Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Push the image on the docker registry
      uses: Ferlab-Ste-Justine/action-push-image@v2
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/clin-maintenance-ui
        tag_format: "{semver}"